=== rsternagel/swev/scenes/scene-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "swev",
  "type": "object",
  "properties": {
    "city": { "type": "string" },
    "latLng": {
      "type": "array",
      "items": { "type": "number" }
    },
    "styles": {
      "type": "array",
       "items": {
         "enum": ["Lindy Hop", "Balboa", "Charleston"]
       }
    },
    "socials": { "type": "boolean" },
    "parties": { "type": "boolean" },
    "courses": { "type": "boolean" },
    "calendarUrl": { "type": "string" },
    "events": {
      "type": "object",
      "properties": {
        "title": { "type": "string" },
        "url": { "type": "string" }
      }
    },
    "groups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": { "type": "string" },
          "url": { "type": "string" },
          "kind": {
            "enum": ["society", "school"]
          },
          "calendarUrl": { "type": "string" }
        }
      }
    }
  },
  "required": [
    "city",
    "latLng",
    "styles",
    "socials",
    "parties",
    "courses",
    "groups"
  ]
}

=== rsternagel/swev/scenes/karlsruhe.json
{
  "city": "Karlsruhe",
  "latLng": [49.006890, 8.403653],
  "styles": ["Lindy Hop", "Charleston"],
  "socials": true,
  "parties": true,
  "courses": true,
  "calendarUrl": "",
  "groups": [
    {
      "title": "Swing in Karlsruhe",
      "url": "http://www.swinginkarlsruhe.de",
      "kind": "society",
      "calendarUrl": "http://www.swinginkarlsruhe.de"
    }
  ]
}
